### ISSUE TITLE
Multiple randomly occurring errors from same XML file

### ISSUE THREAD

**Issue by digininja** [RedSiege/EyeWitness#660] opened 2024-06-04 13:23 UTC
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali rolling up to date.

Latest EW pulled from GitHub this morning and freshly installed.

## Pastebin link to error you are encountering

It completed 120 out of 133 screenshots taking the list from a nmap XML file and then gave this error.

```
Attempting to screenshot http://172.1.4.4
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/robin/tools/EyeWitness/Python/./EyeWitness.py", line 309, in worker_thread
    http_object, driver = capture_host(
  File "/home/robin/tools/EyeWitness/Python/modules/selenium_module.py", line 286, in capture_host
    http_object.source_code = driver.page_source.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/robin/tools/EyeWitness/Python/./EyeWitness.py", line 309, in worker_thread
    http_object, driver = capture_host(
  File "/home/robin/tools/EyeWitness/Python/modules/selenium_module.py", line 223, in capture_host
    opened = urllib.request.urlopen(req, context=context)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.10/http/client.py", line 1259, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object
```

Tried to run it again and got this on a different IP this time. The IP that failed last time appears to have worked OK this run.

```
Attempting to screenshot https://172.1.4.5
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/robin/tools/EyeWitness/Python/./EyeWitness.py", line 309, in worker_thread
    http_object, driver = capture_host(
  File "/home/robin/tools/EyeWitness/Python/modules/selenium_module.py", line 286, in capture_host
    http_object.source_code = driver.page_source.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
Finished in 24.157707452774048 seconds
```

I also got this a bit earlier in the run.

```
Attempting to screenshot http://172.1.3.0
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/robin/tools/EyeWitness/Python/./EyeWitness.py", line 309, in worker_thread
    http_object, driver = capture_host(
  File "/home/robin/tools/EyeWitness/Python/modules/selenium_module.py", line 223, in capture_host
    opened = urllib.request.urlopen(req, context=context)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.10/http/client.py", line 1259, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object
```

I've ran it a few more times and can repeat these errors on different hosts. I've also tried on a different segment of the network with a different XML file and that is giving the same errors at random locations.

This could be three separate issues, but there is likely some link between them so I've lumped the all together. I can split them out into separate issues if I need to.

The network is fairly standard, nothing special on it that I know of.

My guess is that some there is a concurrency issue in something

## Expected behavior (vs. what you encountered)

Don't fail.

**Comment by Relkci** [comment] 2024-06-04 16:11
Can you increase timeout and delay, just curious if that resolves it.

**Comment by digininja** [comment] 2024-06-04 16:25
With a delay of 5 and timeout of 30 it is taking forever, but it is at 130/479 and no errors yet.

I'll report back later hopefully.

**Comment by digininja** [comment] 2024-06-04 17:11
It finally finished with no errors.

**Comment by Relkci** [comment] 2024-06-04 17:21
I'm glad it finished, but now I'm left wondering if it was an EW issue or a system resource / network latency issue.

**Comment by digininja** [comment] 2024-06-04 17:30
It is on a fairly good network, nmap didn't take noticeably longer to scan
than normal.

I have just checked a process list and found a whole load of firefox-esr
and WebExtensions processes left behind. I've just killed them and claimed
back about 3G of ram.

The box is a year old NUC with 8G RAM, I've used similar to scan bigger
networks without any problems..

But I agree, it feels like a resource related issue, either running out or
locking or breaking in some way.

**Comment by Relkci** [comment] 2024-06-04 18:53
Hmm, the dangling processes do sound like a potential problem

**Comment by digininja** [comment] 2024-06-04 19:25
They definitely would be.

**Comment by Relkci** [comment] 2024-06-14 01:30
Returning back to this, I believe that the threads (ten of them, default) all died during the process of accessing the sites and getting an error.  Running again, two more threads died.  Thats twelve outstanding firefox instances with all their associated subprocesses.

I believe this explains the issue with why there were left over processes.

It doesn't explain the original errors you received.  It also highlights that unhandled exceptions don't properly the driver.  In this case it looks like urllib was the offender and it left the webdriver hanging.

If you find a way to consistently reproduce this, I think we can track down what needs to be forced into try/except.

That said, I pushed merged that recently forced a timeout on urllib.  This may inadvertently fix this since it forces urllib to handle socket timeouts differently.

**Comment by digininja** [comment] 2024-06-14 08:01
I've moved off that network now so I can't re-test this, but it was
definitely something special either about that network or the box I was
running it from.

The box is a NUC with 8G and a new'ish processor so not underpowered but it
is the first time I've used it to scan from. It is currently supposed to be
heading home from the Maldives so if it ever makes it back I can test it
again.

The network wasn't anything special, all the other tools ran fine on it.
I've scanned much bigger networks from similar spec boxes without any
problems.

Hopefully it was a one off and the lack of exception handling can get
sorted to generally improve the app.

I'm happy to close this or leave it open if you want to do some more work
on it and reference it.

**Comment by Relkci** [comment] 2024-06-14 20:29
Looking closely, I see that the Try: Except: case for urllib on selenium_module.py actually has lots of exception catches, but doesn't have a final catch-all.  If we aren't explicitly handling the exception type, we'll get the python trace on the unhandled error.  

~Try on line 216 needs additional exception handling -- probably a final catch all for odd cases like this.
Currently we catch urllib.error.URLError, urllib.error.HTTPError, socket.error, http.client.badstatusline, and sslerr. -- so clearly we're missing some subclass exceptions that are left unhandled.  

It looks like the python trace you have ends with a TypeError subclass.

Clearly there was something else in the process that caused client.py to not properly handle the data, but if we add TypeError, I think that would at least handle this situation.

@digininja Coincidentally, if you look in the screens folder, I'm guessing selenium properly captured the screenshot.  the error occurred after the screenshot when urllib grabs headers and source.

**Comment by digininja** [comment] 2024-06-14 20:36
I've got all the data, I'll look tomorrow. I should be able to work out
which directory is for which error.

**Comment by Relkci** [comment] 2024-06-14 21:12
The screen for whatever site it was will be in the screens folder named with the IP.  The report likely did not include the screenshot because urllib errored.  I opened #671 to address report generation where a screenshot was generated by urllib failed to capture data.

**Comment by digininja** [comment] 2024-06-18 08:30
Assuming the error happened trying to screenshot the host directly above where the error happened, none of them have screenshots.

```
$ find . -name '*16.62.0*'
./eyewtest1/source/https.172.16.62.0.txt
./eyewtest1/source/http.172.16.62.0.txt
./eyew2/source/https.172.16.62.0.txt
./eyew2/source/http.172.16.62.0.txt
$ find . -name '*172.1.4.4*'
$ find . -name '*172.1.4.5*'
$ find . -name '*172.1.3.0*'
```

**Comment by Relkci** [comment] 2024-06-18 18:28
interesting. anyway, I merged the exception catch on 670.  If it happens again, create a new issue please.

**Closed by Relkci** 2024-06-18 18:28 UTC
Labels: bug, fix-planned, python

**Comment by digininja** [comment] 2024-06-18 18:34
Will do
